controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_verify_email:
    path: /verify-email
    controller: App\Controller\VerifyEmailController::verify
